<a href="https://colab.research.google.com/github/sarabdar/pytorch/blob/main/Linear_Regression_using_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# Equation:
$b=-1,w=2$

$\hat{y}=-1+2x$

In [2]:
# Define w = 2 and b = -1 for y = wx + b

w = torch.tensor(2.0, requires_grad = True)
b = torch.tensor(-1.0, requires_grad = True)

In [3]:
# Function forward(x) for prediction

def forward(x):
    yhat = w * x + b
    return yhat

### Lets make the prediction at x= 1
$\hat{y}=-1+2x$

$\hat{y}=-1+2(1)$

In [4]:
# Predict y = 2x - 1 at x = 1

x = torch.tensor([[1.0]])
yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[1.]], grad_fn=<AddBackward0>)


In [5]:
# Create x Tensor and check the shape of x tensor

x = torch.tensor([[1.0], [2.0]])
print("The shape of x: ", x.shape)

The shape of x:  torch.Size([2, 1])


In [6]:
# Make the prediction of y = 2x - 1 at x = [1, 2]

yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


# Torch also provides a build-in Linear class

In [15]:
from torch.nn import Linear
torch.manual_seed(1)

In [22]:
lr = Linear(in_features=1, out_features=1, bias=True)
print("Parameters w and b: ", list(lr.parameters()))

Parameters w and b:  [Parameter containing:
tensor([[0.3652]], requires_grad=True), Parameter containing:
tensor([-0.3897], requires_grad=True)]


In [23]:
print("Python dictionary: ",lr.state_dict())
print("keys: ",lr.state_dict().keys())
print("values: ",lr.state_dict().values())

Python dictionary:  OrderedDict({'weight': tensor([[0.3652]]), 'bias': tensor([-0.3897])})
keys:  odict_keys(['weight', 'bias'])
values:  odict_values([tensor([[0.3652]]), tensor([-0.3897])])


In [24]:
print("weight:",lr.weight)
print("bias:",lr.bias)

weight: Parameter containing:
tensor([[0.3652]], requires_grad=True)
bias: Parameter containing:
tensor([-0.3897], requires_grad=True)


In [25]:
# Make the prediction at x = [[1.0]]

x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[-0.0245]], grad_fn=<AddmmBackward0>)


In [26]:
# Create the prediction using linear model

x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[-0.0245],
        [ 0.3408]], grad_fn=<AddmmBackward0>)


# Build custom models

In [27]:
from torch import nn

In [28]:
# Customize Linear Regression Class

class LR(nn.Module):

    # Constructor
    def __init__(self, input_size, output_size):

        # Inherit from parent
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)

    # Prediction function
    def forward(self, x):
        out = self.linear(x)
        return out

In [29]:
# Create the linear regression model. Print out the parameters.

lr = LR(1, 1)
print("The parameters: ", list(lr.parameters()))
print("Linear model: ", lr.linear)

The parameters:  [Parameter containing:
tensor([[-0.0729]], requires_grad=True), Parameter containing:
tensor([-0.0900], requires_grad=True)]
Linear model:  Linear(in_features=1, out_features=1, bias=True)


In [30]:
# Try our customize linear regression model with single input

x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[-0.1629]], grad_fn=<AddmmBackward0>)


In [31]:
# Try our customize linear regression model with multiple input

x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[-0.1629],
        [-0.2358]], grad_fn=<AddmmBackward0>)


In [32]:
print("Python dictionary: ", lr.state_dict())
print("keys: ",lr.state_dict().keys())
print("values: ",lr.state_dict().values())

Python dictionary:  OrderedDict({'linear.weight': tensor([[-0.0729]]), 'linear.bias': tensor([-0.0900])})
keys:  odict_keys(['linear.weight', 'linear.bias'])
values:  odict_values([tensor([[-0.0729]]), tensor([-0.0900])])
