<a href="https://colab.research.google.com/github/sarabdar/pytorch/blob/main/Tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# These are the libraries will be used for this lab.
import numpy as np
import pandas as pd
import torch

import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
torch.__version__

'2.10.0+cpu'

In [ ]:
tensor_object = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Shape of the tensor is: ", tensor_object.shape)
print("dtype of tensor is : ",tensor_object.dtype)
print("The tensor object is : ",tensor_object)
print("type of tensor object is: ",tensor_object.type())

Shape of the tensor is:  torch.Size([3, 3])
dtype of tensor is :  torch.int64
The tensor object is :  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
type of tensor object is:  torch.LongTensor


In [ ]:
type(tensor_object)

torch.Tensor

In [ ]:
# Convert a float list with length 5 to a tensor

floats_to_tensor = torch.tensor([0.0, 1.0, 2.0, 3.0, 4.0])
print("The dtype of tensor object after converting it to tensor: ", floats_to_tensor.dtype)
print("The type of tensor object after converting it to tensor: ", floats_to_tensor.type())

The dtype of tensor object after converting it to tensor:  torch.float32
The type of tensor object after converting it to tensor:  torch.FloatTensor


In [ ]:
float_tensor = torch.tensor([0.0, 0.1, 0.2, 0.3, 0.4])
print("The dtype of tensor object after converting it to tensor: ", float_tensor.dtype)
print("The type of tensor object after converting it to tensor: ", float_tensor.type())
print(float_tensor)

print("------------------------------------")
print("------------------------------------")
print("------------------------------------")
print("------------------------------------")

float_int_tensor = torch.tensor([0.0, 0.1, 0.2, 0.3, 0.4], dtype=torch.int32)
print("The dtype of tensor object after converting it to tensor: ", float_int_tensor.dtype)
print("The type of tensor object after converting it to tensor: ", float_int_tensor.type())
print(float_int_tensor)


print("------------------------------------")
print("------------------------------------")
print("------------------------------------")
print("------------------------------------")
# Now lets try to conver the int tensor into float
print("Now lets try to conver the int tensor into float")
float_tensor = float_int_tensor.to(torch.float32)
print("The dtype of tensor object after converting it to tensor: ", float_tensor.dtype)
print("The type of tensor object after converting it to tensor: ", float_tensor.type())
print(float_tensor)

The dtype of tensor object after converting it to tensor:  torch.float32
The type of tensor object after converting it to tensor:  torch.FloatTensor
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000])
------------------------------------
------------------------------------
------------------------------------
------------------------------------
The dtype of tensor object after converting it to tensor:  torch.int32
The type of tensor object after converting it to tensor:  torch.IntTensor
tensor([0, 0, 0, 0, 0], dtype=torch.int32)
------------------------------------
------------------------------------
------------------------------------
------------------------------------
Now lets try to conver the int tensor into float
The dtype of tensor object after converting it to tensor:  torch.float32
The type of tensor object after converting it to tensor:  torch.FloatTensor
tensor([0., 0., 0., 0., 0.])


In [ ]:
old_int_tensor = torch.tensor([0, 1, 2, 3, 4, 5])
new_float_tensor = old_int_tensor.type(torch.FloatTensor)
print("The type of the new_float_tensor:", new_float_tensor.type())
print("Size of of new_float_tensor is: ", new_float_tensor.size())
print("Dimensions of the tensor are: ", new_float_tensor.ndimension())

The type of the new_float_tensor: torch.FloatTensor
Size of of new_float_tensor is:  torch.Size([6])
Dimensions of the tensor are:  1


In [ ]:
# Now converting the tensor to a 2D
new_2D_tensor = new_float_tensor.view(-1, 2)
print(new_2D_tensor)
print("Size of the new_2D_tensor is: ", new_2D_tensor.size())
print("Dimensions of the tensor are: ", new_2D_tensor.ndimension())

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])
Size of the new_2D_tensor is:  torch.Size([3, 2])
Dimensions of the tensor are:  2


In [ ]:
# Now changing it into a numpy array

back_to_numpy = new_2D_tensor.numpy()
print("The numpy array from tensor: ", back_to_numpy)
print("The dtype of numpy array: ", back_to_numpy.dtype)

The numpy array from tensor:  [[0. 1.]
 [2. 3.]
 [4. 5.]]
The dtype of numpy array:  float32


In [ ]:
# Convert a panda series to a tensor

pandas_series=pd.Series([0.1, 2, 0.3, 10.1])
new_tensor=torch.from_numpy(pandas_series.values)
print("The new tensor from numpy array: ", new_tensor)
print("The dtype of new tensor: ", new_tensor.dtype)
print("The type of new tensor: ", new_tensor.type())

The new tensor from numpy array:  tensor([ 0.1000,  2.0000,  0.3000, 10.1000], dtype=torch.float64)
The dtype of new tensor:  torch.float64
The type of new tensor:  torch.DoubleTensor
